// fixtures/reference/sveltekit-basic/src/routes/dashboard/+page.svelte
<script lang="ts">
  import StatCard from '$lib/components/StatCard.svelte';
  import { formatNumber } from '$lib/utils/format';

  export let data: { stats: Array<{ label: string; value: number }> };
</script>

<section>
  <h1>Dashboard</h1>
  {#each data.stats as stat (stat.label)}
    <StatCard label={stat.label} value={formatNumber(stat.value)} />
  {/each}
</section>

// fixtures/reference/nuxt-dashboard-basic/pages/dashboard.vue
<script setup lang="ts">
// File-system route: GET /dashboard. StatCard is auto-imported via Nuxt
// components/ convention (nested under components/dashboard/).
import { useStats } from '~/composables/useStats';
import { formatNumber } from '~/utils/format';

const { stats } = useStats();
</script>

<template>
  <section>
    <h1>Dashboard</h1>
    <StatCard v-for="s in stats" :key="s.label" :label="s.label" :value="formatNumber(s.value)" />
  </section>
</template>
