// fixtures/reference/react-spa-basic/src/components/Header.tsx
import { Link } from 'react-router-dom';
import { SearchIcon } from './icons/SearchIcon';
import { cn } from '../utils/cn';

export function Header(): JSX.Element {
  return (
    <header className={cn('app-header', 'border-b')}>
      <Link to="/">Home</Link>
      <Link to="/settings">Settings</Link>
      <Link to="/profile">Profile</Link>
      <SearchIcon />
    </header>
  );
}

// fixtures/reference/svelte-spa-basic/src/lib/components/Header.svelte
<script lang="ts">
  import SearchIcon from './SearchIcon.svelte';
  import { cn } from '$lib/utils/cn';

  export let route: 'home' | 'settings' | 'profile' = 'home';
</script>

<header class={cn('app-header', 'border-b')}>
  <button on:click={() => (route = 'home')}>Home</button>
  <button on:click={() => (route = 'settings')}>Settings</button>
  <button on:click={() => (route = 'profile')}>Profile</button>
  <SearchIcon />
</header>
