// fixtures/reference/tanstack-router-basic/src/routes/dashboard.tsx
import { useStats } from '../hooks/useStats';
import { StatCard } from '../components/StatCard';
import { formatNumber } from '../lib/format';

export function DashboardPage(): JSX.Element {
  const { data } = useStats();
  return (
    <section>
      <h1>Dashboard</h1>
      {data?.map((s) => (
        <StatCard key={s.label} label={s.label} value={formatNumber(s.value)} />
      ))}
    </section>
  );
}

// fixtures/reference/sveltekit-basic/src/routes/dashboard/+page.svelte
<script lang="ts">
  import StatCard from '$lib/components/StatCard.svelte';
  import { formatNumber } from '$lib/utils/format';

  export let data: { stats: Array<{ label: string; value: number }> };
</script>

<section>
  <h1>Dashboard</h1>
  {#each data.stats as stat (stat.label)}
    <StatCard label={stat.label} value={formatNumber(stat.value)} />
  {/each}
</section>
