// fixtures/reference/svelte-spa-basic/src/App.svelte
<script lang="ts">
  import Header from '$lib/components/Header.svelte';
  import HomePage from './routes/HomePage.svelte';
  import { theme } from '$lib/stores/theme';

  // Lazy-loaded route — Svelte uses await import() in {#await} blocks.
  const SettingsPagePromise = import('./routes/SettingsPage.svelte');
  const ProfilePagePromise = import('./routes/ProfilePage.svelte');

  let route: 'home' | 'settings' | 'profile' = 'home';
</script>

<div data-theme={$theme}>
  <Header bind:route />
  {#if route === 'home'}
    <HomePage />
  {:else if route === 'settings'}
    {#await SettingsPagePromise then mod}
      <svelte:component this={mod.default} />
    {/await}
  {:else if route === 'profile'}
    {#await ProfilePagePromise then mod}
      <svelte:component this={mod.default} />
    {/await}
  {/if}
</div>

// fixtures/reference/react-spa-basic/src/App.tsx
import { lazy, Suspense } from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import { Header } from './components/Header';
import { HomePage } from './routes/HomePage';
import { useTheme } from './hooks/useTheme';

// Code-split routes — these import calls must be picked up as dynamic edges,
// otherwise the route components look like dead code.
const SettingsPage = lazy(() => import('./routes/SettingsPage'));
const ProfilePage = lazy(() => import('./routes/ProfilePage'));

export function App(): JSX.Element {
  const { theme } = useTheme();
  return (
    <BrowserRouter>
      <div data-theme={theme}>
        <Header />
        <Suspense fallback={<div>Loading…</div>}>
          <Routes>
            <Route path="/" element={<HomePage />} />
            <Route path="/settings" element={<SettingsPage />} />
            <Route path="/profile" element={<ProfilePage />} />
          </Routes>
        </Suspense>
      </div>
    </BrowserRouter>
  );
}
